### PR TITLE
Fix/safari audio context

### PR DESCRIPTION
**Pull request by etienne-lelouet**
Redefined AudioContext using webkit so safari can use it.
image

### CODE REVIEW

**Comment by LovaszNorbert** [comment]
Can Someone merge this and publish it to npm?

**Comment by buzinas** [comment]
@LovaszNorbert I'll publish the new version to NPM soon.

**Comment by danirrivas** [comment]
Can someone please merge this and publish it to npm?
Thanks!

**Comment by francisco-genially** [comment]
@buzinas can you publish a new version with this fix to npm?
Thanks!

**Pull request merged**
