### PR TITLE
BUG: package dont ask for premission on mobile

### PR DESCRIPTION
**Pull request by Mamoanwar97**

### CODE REVIEW

**Comment by Mamoanwar97** [comment]
@buzinas please can you upload this to the npm package? This is a minior bug that will differ really much 🙏

**Comment by buzinas** [comment]
@mamoanwar97 If you don't pass any `deviceId`, it's already setting `audio: true`, as you can see a couple of lines above:

```js
const audio = this.config.deviceId ? { deviceId: { exact: this.config.deviceId } } : true;
```

**Comment by Mamoanwar97** [comment]
for some reason this isnot working on my project, it was working fine on laptops but on mobile phones it didn't work it wasn't asking for permission until I changed 

```
navigator.mediaDevices.getUserMedia({ audio: audio })
```
to 
```
navigator.mediaDevices.getUserMedia({ audio: true })
```
thanks anyway for this library

**Comment by buzinas** [comment]
And what shows up when you `console.log(audio)`?

**Pull request closed without merging**
